[package]
name = "test_storage"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
tikv = { path = "../../" }
test_raftstore = { path = "../test_raftstore" }
kvproto = { git = "https://github.com/MyonKeminta/kvproto.git", branch="misono/prewrite-response-with-ts" }
futures = "0.1"
